# This workflow will build a golang project
# For more information see: http://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Computer

on:
  push:
    - "start"
      
jobs:
  create-release:
    runs-on: windows-latest
    
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      
    - name: Setup
      uses: actions/setup-go@v3
    
    - name: Build Cross
      run: "./buildcross.bat"
    
    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        body_path: ./CHANGELOG.md
        draft: false
        prerelease: false
        files: |
          ./releases/*
