name: CiliXiazai_many

on:
  push:
    tags:
      - "cili.*"
jobs:
  start:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      
    # 设置Node环境 actions/setup-node@v1 是GitHub Marketplace其中的一个,相当于一个方法
    # 使用一个Actions 使用uses关键字,  with表明参数
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
 
    # 使用多路径的缓存帮助构建
    - name: Cache multiple paths
      uses: actions/cache@v2
      with:
        path: |
          ~/cache
          !~/cache/exclude
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      
    - name: Xiazai_cili
      run: |
        chmod +x CiliXiazai.sh
        ./CiliXiazai.sh
        
    - name: Create GitHub release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ env.ReleaseVersion }}
        title: ${{ env.ReleaseVersion }}
        prerelease: false
        files: |
          ./download/*