name: Computer

on:
  push:
    tags:
      - "*"
      
jobs:
  start:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      
    - name: Dl
      run: |
        mkdir ./download
        mkdir ./cache
        wget -P ./cache -i ./download_list.txt
        cd ./cache
        tar -zcvf - output/* | split -d -b 1G - ../download/
              
    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        body: Download
        draft: false
        prerelease: false
        files: |
          ./download/*
