name: HttpXiazai

on:
  push:
    tags:
      - "http.*"
      
jobs:
  start:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
            
    - name: Xiazai_http
      run: |
        mkdir ./download
        cd ./download
        wget -q https://releases.ubuntu.com/22.04.1/ubuntu-22.04.1-desktop-amd64.iso
        echo ====folder ./download====
        ls
        fname=$(ls  *.*)
        echo ====name of download file====
        echo $fname
        echo ====split file====
        split -b1999M --verbose $fname $fname\_
        echo ====after split====
        ls
        rm -f $fname
        echo ====after remove original file====
        ls
        
    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        body: Download
        draft: false
        prerelease: false
        files: |
          ./download/*
